// Version 3.0 by Chooka https://github.com/Chooka/obs-shaderfilter.git
// Version 2.0 by Exeldro https://github.com/exeldro/obs-shaderfilter
// Version 1.21 by Charles Fettinger https://github.com/Oncorporation/obs-shaderfilter
// original version by nleseul https://github.com/nleseul/obs-shaderfilter

#include "shader_filter_templates.h"

const char *effect_template_begin = "uniform float4x4 ViewProj;\n"
				    "uniform texture2d image;\n"
				    "\n"
				    "uniform float2 uv_offset;\n"
				    "uniform float2 uv_scale;\n"
				    "uniform float2 uv_pixel_interval;\n"
				    "uniform float2 uv_size;\n"
				    "uniform float rand_f;\n"
				    "uniform float rand_instance_f;\n"
				    "uniform float rand_activation_f;\n"
				    "uniform float elapsed_time;\n"
				    "uniform float elapsed_time_start;\n"
				    "uniform float elapsed_time_show;\n"
				    "uniform float elapsed_time_active;\n"
				    "uniform float elapsed_time_enable;\n"
				    "uniform int loops;\n"
				    "uniform float loop_second;\n"
				    "uniform float local_time;\n"
				    "\n"
				    "sampler_state textureSampler{\n"
				    "\tFilter = Linear;\n"
				    "\tAddressU = Border;\n"
				    "\tAddressV = Border;\n"
				    "\tBorderColor = 00000000;\n"
				    "};\n"
				    "\n"
				    "struct VertData {\n"
				    "\tfloat4 pos : POSITION;\n"
				    "\tfloat2 uv : TEXCOORD0;\n"
				    "};\n"
				    "\n"
				    "VertData mainTransform(VertData v_in)\n"
				    "{\n"
				    "\tVertData vert_out;\n"
				    "\tvert_out.pos = mul(float4(v_in.pos.xyz, 1.0), ViewProj);\n"
				    "\tvert_out.uv = v_in.uv * uv_scale + uv_offset;\n"
				    "\treturn vert_out;\n"
				    "}\n"
				    "\n"
				    "float srgb_nonlinear_to_linear_channel(float u)\n"
				    "{\n"
				    "\treturn (u <= 0.04045) ? (u / 12.92) : pow((u + 0.055) / 1.055, 2.4);\n"
				    "}\n"
				    "\n"
				    "float3 srgb_nonlinear_to_linear(float3 v)\n"
				    "{\n"
				    "\treturn float3(srgb_nonlinear_to_linear_channel(v.r),\n"
				    "\t              srgb_nonlinear_to_linear_channel(v.g),\n"
				    "\t              srgb_nonlinear_to_linear_channel(v.b));\n"
				    "}\n";

const char *effect_template_default_image_shader = "float4 mainImage(VertData v_in) : TARGET\n"
						   "{\n"
						   "\treturn image.Sample(textureSampler, v_in.uv);\n"
						   "}\n";

const char *effect_template_default_transition_image_shader = "uniform texture2d image_a;\n"
							      "uniform texture2d image_b;\n"
							      "uniform float transition_time = 0.5;\n"
							      "uniform bool convert_linear = true;\n"
							      "\n"
							      "float4 mainImage(VertData v_in) : TARGET\n"
							      "{\n"
							      "\tfloat4 a_val = image_a.Sample(textureSampler, v_in.uv);\n"
							      "\tfloat4 b_val = image_b.Sample(textureSampler, v_in.uv);\n"
							      "\tfloat4 rgba = lerp(a_val, b_val, transition_time);\n"
							      "\tif (convert_linear)\n"
							      "\t\trgba.rgb = srgb_nonlinear_to_linear(rgba.rgb);\n"
							      "\treturn rgba;\n"
							      "}\n";

const char *effect_template_end = "technique Draw\n"
				  "{\n"
				  "\tpass\n"
				  "\t{\n"
				  "\t\tvertex_shader = mainTransform(v_in);\n"
				  "\t\tpixel_shader = mainImage(v_in);\n"
				  "\t}\n"
				  "}\n";
